### PR TITLE
Print URL to console

### PR DESCRIPTION
**Pull request by DerZersaeger**
Like in yarn

https://classic.yarnpkg.com/en/docs/cli/upgrade-interactive/

### CODE REVIEW

**Comment by ondrejfuhrer** [comment]
Hello @DerZersaeger , thank you for the contribution! 👍 
My question is, what would be the benefit of having it? Why would you like to see the URL in the output?

My concern is that with certain casks installed the output is already quite wide (yes, looking at you, [Java](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb#L2)!). So by adding more information the output will start wrapping into new lines making the output less readable.

How about adding that columns in verbose mode only? Would that make sense?

**Comment by yurikoles** [comment]
When I saw PR title my first impression was that this related to parallel downloads ticket.

@DerZersaeger @ondrejfuhrer 

Could you please also implement an option that will generate a download URLs with corresponding target files locations?

I'm also volunteering here, so advice will be very appreciated.

**Comment by yurikoles** [comment]
Here is how it looks on my scaled terminal with large font.
proof

**Comment by ondrejfuhrer** [comment]
So it is actually trimming the result so those URLs won't actually work, am I right here?

> Could you please also implement an option that will generate a download URLs with corresponding target files locations?

Well, those URLs are even longer (imagine when the cask is downloaded from S3), what would be the use case here?

**Comment by yurikoles** [comment]
> Well, those URLs are even longer (imagine when the cask is downloaded from S3), what would be the use case here?

This output is not for humans, it's intended to be supplied to third party downloader.

**Comment by ondrejfuhrer** [comment]
@yurikoles So something like this?
```bash
> brew cu download-links
https://page1.com/application1.dmg
https://page2.com/application2.dmg
https://page3.com/application3.dmg
```

And then you would pipe that into another command to do your magic?

**Comment by yurikoles** [comment]
@ondrejfuhrer 
Yes, but I'm also thinking about file names, because `brew` generates path by adding some hash in front. The `~/Library/Caches/Homebrew/downloads/` may be assumed or gotten with `brew --cache`.

**Comment by yurikoles** [comment]
@DerZersaeger sorry for hijacking thread :(

@ondrejfuhrer let's continue in #160

**Comment by DerZersaeger** [comment]
> @DerZersaeger sorry for hijacking thread :(
> 
> @ondrejfuhrer let's continue in #160

No problem

**Comment by DerZersaeger** [comment]
> Hello @DerZersaeger , thank you for the contribution! 👍
> My question is, what would be the benefit of having it? Why would you like to see the URL in the output?
> 
> My concern is that with certain casks installed the output is already quite wide (yes, looking at you, [Java](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb#L2)!). So by adding more information the output will start wrapping into new lines making the output less readable.
> 
> How about adding that columns in verbose mode only? Would that make sense?

My intention is:
When I upgrade any cask(s) I want to see what have changed.

E.g. when I run `brew cu -a -f` and see that `vscodium` or `rectangle` is outdated, I have to find the corresponding repository and check the committed changes.

I'm just too lazy to search all the time for these repos, so I started with this PR.

**Comment by DerZersaeger** [comment]
> How about adding that columns in verbose mode only? Would that make sense?
@ondrejfuhrer 

See: https://github.com/buo/homebrew-cask-upgrade/pull/162/commits/91b2e6b69128e3537698e2f2f5d146802f804a69

Grüße nach Berlin 🇩🇪  😄 👍

**Pull request merged**
