### PR TITLE
Make GitHub Actions to be read-only

### PR DESCRIPTION
**Pull request by yurikoles**
Make GitHub Actions to be read-only[0].

[0]https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

### CODE REVIEW

**Review by ondrejfuhrer — COMMENTED** [review]
Haven't really checked what does that affect - can you elaborate a little bit on that? I don't have that much experience with GH actions.

**Comment by yurikoles** [comment]
By default, GHA uses token with write access to some of repo's scopes, so limiting it to a necessary minimum is a good practice.

**Comment by ondrejfuhrer** [comment]
@yurikoles that makes sense. Just wasn't sure exactly what does it affect 🙂

**Comment by yurikoles** [comment]
Oh, I forgot to post a proof, so [before this PR](https://github.com/buo/homebrew-cask-upgrade/actions/runs/2642737913) GHA logged in `Set up job`:

```
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```

After:

```
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
```

**Pull request merged**
