### PR TITLE
Adding resiliency to `nil` version

### LINKED ISSUE #221: Undefinded method for nil:NilClass
Get this error message: 

```sh 
$ brew cu 
==> Options
Include auto-update (-a): true
Include latest (-f): false
==> Updating Homebrew
Already up-to-date.
Error: undefined method `before_separators' for nil:NilClass
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:23:in `block in installed_apps'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:13:in `map'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:13:in `installed_apps'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:29:in `run_process'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:8:in `process'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:25:in `process'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:72:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/utils.rb:92:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:92:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```
I'm not really found any solution in the world wide web. 

System: MacOS Mojave 10.14.6
Shell: zsh

### PR DESCRIPTION
**Pull request by ondrejfuhrer**
This adds a bit of resiliency to missing version.

Fixes #221

### CODE REVIEW

**Comment by muescha** [comment]
you are sure that if there is no version that the directory structure for installed casks are also in versions?

```ruby
      versions = installed_versions(token)
      current_version = DSL::Version.new(versions.first)
```

**Comment by muescha** [comment]
https://github.com/buo/homebrew-cask-upgrade/blob/bed5779cfed3db5e65acea1144a6d68e5ff84596/lib/extend/cask.rb#L13

i would suggest to print here the `token` if the option is `--verbose` - then it is more easy to find the first failing cask token

**Comment by ondrejfuhrer** [comment]
> you are sure that if there is no version that the directory structure for installed casks are also in versions?
> 
> ```ruby
>       versions = installed_versions(token)
>       current_version = DSL::Version.new(versions.first)
> ```

To be honest I only fixed what was reported in the issue and other similar places (chaining calls where the result of previous could be nil). Not sure what exactly are you suggesting here?

**Comment by muescha** [comment]
> Not sure what exactly are you suggesting here?

If there is a cask where "version" = nil then brew can not construct a path like `/{token}/{version}/` 

Then also the path construct maybe broken or the path not include a version number. That's why I guess this line may also break 🤷‍♂️

**Comment by ondrejfuhrer** [comment]
> > Not sure what exactly are you suggesting here?
> 
> 
> 
> If there is a cask where "version" = nil then brew can not construct a path like `/{token}/{version}/` 
> 
> 
> 
> Then also the path construct maybe broken or the path not include a version number. But the implementation of `installed_versions` is based on this path schema.  That's why I guess this line may also break 🤷‍♂️ or the `DSL::Version` when there is nil or something strange value

Ah, ok, makes sense. However in that case the glob function returns empty array no matter what you throw at it (except invalid characters for path I believe). 

In this case, since it went through to next lines, it doesn't break in this case. 

But thanks for calling it out 🙂

**Pull request merged**
