### PR TITLE
Fixes #109 Replace require "hbc" with "cask/all"

### LINKED ISSUE #109: brew cu fails with "Error: cannot load such file -- hbc"
Repro:

1. Run `brew cu`

Expected: normal run
Instead: it fails with runtime error

Console output:

```
⋊> ~  brew cu                                                                                                                                                                                           14:00:29
Error: cannot load such file -- hbc
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:4:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

### LINKED ISSUE #111: Error: cannot load such file -- hbc
when i execute `brew cu -y -a` i get an error
```bash
Error: cannot load such file -- hbc
```

# reproduce
```bash
$ cd "$(brew --repo)
$ git fetch
$ git reset --hard origin/master
HEAD is now at 817b72d5b Merge pull request #4807 from MikeMcQuaid/cask-move
$ brew update
Already up-to-date.

$ brew cu -y -a
Error: cannot load such file -- hbc
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:4:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

i saw https://github.com/buo/homebrew-cask-upgrade/issues/12 but it is not really helpful.

can someone please confirm the issue?
shall i file a bug?

### PR DESCRIPTION
**Pull request by ondrejfuhrer**
Fixes #109 
Fixes #111

### CODE REVIEW

**Comment by greveritt** [comment]
Thanks so much for this. I will use your branch for now, @ondrejfuhrer , as you suggested in the issue thread.

**Comment by idoo** [comment]
@buo any chance to get it merged?

**Comment by buo** [comment]
@ondrejfuhrer Thank you for your contribution as always. You are awesome :)

**Comment by greveritt** [comment]
Yes, @ondrejfuhrer, thank you! 😄

**Comment by ondrejfuhrer** [comment]
@buo @greveritt Welcome 🙂 Always happy to help out

**Pull request merged**
